import Head from 'next/head'
import Header from '../components/Header'

export default function Home(user: {}) {
  console.log(user)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:5000/auth')
  const user = await res.json()
  return {
    props: user
  }
}
